os: linux
dist: bionic
language: python
python: "3.6"
addons:
  apt:
    packages:
      - libx11-dev
      - libxi-dev
      - gcc
      - clang
env:
  - CC=gcc MESON_OPTIONS="--default-library=static"
  - CC=gcc MESON_OPTIONS="--default-library=shared"
  - CC=clang MESON_OPTIONS="--default-library=static"
  - CC=clang MESON_OPTIONS="--default-library=shared"

before_script:
  - pip install ninja meson
script:
  - meson --buildtype=debugoptimized ${MESON_OPTIONS} -DSDL=enabled build
  - ninja -C build
before_deploy:
  - DESTDIR=`realpath eva` ninja -C build install
  - export TRAVIS_FILENAME="eva-${TRAVIS_OS_NAME}-${TRAVIS_TAG}.tar.gz"
  - tar -czvf $TRAVIS_FILENAME eva
deploy:
  provider: releases
  api_key: $GITHUB_PAT
  file: $TRAVIS_FILENAME
  on:
    tags: true
  skip_cleanup: true
